export const ROW_DELETE = 'ROW_DELETE';
export const COL_DELETE = 'COL_DELETE';
export const CELL_EDIT = 'CELL_EDIT';
export const SORT_COL_DESC = 'SORT_COL_DESC';
export const SORT_COL_ASC = 'SORT_COL_ASC';
export const SELECT_ROW = 'SELECT_ROW';
export const UNSELECT_ROW = 'UNSELECT_ROW';
export const SELECT_COL = 'SELECT_COL';
export const UNSELECT_COL = 'UNSELECT_COL';
export const UNSELECT_ALL_ROW = 'UNSELECT_ALL_ROW';
export const UNSELECT_ALL_COL = 'UNSELECT_ALL_COL';
export const SELECTE_CELL = 'SELECTE_CELL';
export const UNSELECT_CELL = 'UNSELECT_CELL';
export const UNSELECT_ALL_CELL = 'UNSELECT_ALL_CELL';
export const SCROLL_BOTTOM_UPDATE_DATA = 'SCROLL_BOTTOM_UPDATE_DATA';
export const SCROLL_TOP_UPDATE_DATA = 'SCROLL_TOP_UPDATE_DATA';



